# Generated by Django 3.0.1 on 2020-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20200329_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional')], max_length=25),
        ),
    ]
